---
# tasks file for haproxy
          

          - name: "Create a directory"
            file:
                  state: directory
                  path: "/dvd1"
          - name: "Mount the iso file to directory created"
            mount:
                  src: "/dev/cdrom"
                  path: "/dvd1"
                  state: mounted
                  fstype: iso9660
          - name: "Yum config for Appstream"
            yum_repository:
                  baseurl: "/dvd1/AppStream"
                  name: "mydvd"
                  description: "my yum dvd for AppStream"
                  gpgcheck: no
          - name: "yum config for BaseOS"
            yum_repository:
                  baseurl: "/dvd1/BaseOS"
                  name: "mydvd2"
                  description: "my yum dvd2 for baseOS"
                  gpgcheck: no
          - name: "Install Haproxy"
            package:
                  name: "haproxy"
                  state: present


          - name: " Haproxy cfg"
            template:
                  dest: "/etc/haproxy/haproxy.cfg"
                  src: "/ws1/load_b/haproxy.cfg.j2"
            notify: "Restart Haproxy"

          - name: "Enable firewall"
            service:
                  name: "firewalld"
                  state: started
                  enabled: yes
          - name: "Add http Firewall Rule"
            firewalld:
                  port: "{{  frontend_main_port  }}/tcp"
                  state: enabled
                  permanent: yes
                  immediate: yes


          - name: "Start Haproxy service"
            service:
                  name: "haproxy"
                  state: started


